ren D:\IdeaProjects\IDLua\src\nginx.png Lua.png
ren D:\IdeaProjects\IDLua\src\NginxBundle.properties LuaBundle.properties
ren D:\IdeaProjects\IDLua\src\annotator\NginxElementVisitor.java LuaElementVisitor.java
ren D:\IdeaProjects\IDLua\src\parser\NginxParser.java LuaParser.java
ren D:\IdeaProjects\IDLua\src\parser\NginxParserDefinition.java LuaParserDefinition.java
ren D:\IdeaProjects\IDLua\src\platform\NginxCompileParameters.java LuaCompileParameters.java
ren D:\IdeaProjects\IDLua\src\platform\NginxCompileParametersExtractor.java LuaCompileParametersExtractor.java
ren D:\IdeaProjects\IDLua\src\psi\impl\NginxComplexValueImpl.java LuaComplexValueImpl.java
ren D:\IdeaProjects\IDLua\src\psi\impl\NginxContextImpl.java LuaContextImpl.java
ren D:\IdeaProjects\IDLua\src\psi\impl\NginxDirectiveImpl.java LuaDirectiveImpl.java
ren D:\IdeaProjects\IDLua\src\psi\impl\NginxDirectiveNameImpl.java LuaDirectiveNameImpl.java
ren D:\IdeaProjects\IDLua\src\psi\impl\NginxDirectiveValueImpl.java LuaDirectiveValueImpl.java
ren D:\IdeaProjects\IDLua\src\psi\impl\NginxDirectiveValueManipulator.java LuaDirectiveValueManipulator.java
ren D:\IdeaProjects\IDLua\src\psi\impl\NginxElementImpl.java LuaElementImpl.java
ren D:\IdeaProjects\IDLua\src\psi\impl\NginxInnerVariableImpl.java LuaInnerVariableImpl.java
ren D:\IdeaProjects\IDLua\src\psi\impl\NginxPsiFileImpl.java LuaPsiFileImpl.java
ren D:\IdeaProjects\IDLua\src\run\NginxConfigurationType.java LuaConfigurationType.java
ren D:\IdeaProjects\IDLua\src\run\NginxConsoleFilter.java LuaConsoleFilter.java
ren D:\IdeaProjects\IDLua\src\run\NginxExecutionResult.java LuaExecutionResult.java
ren D:\IdeaProjects\IDLua\src\run\NginxLogTab.java LuaLogTab.java
ren D:\IdeaProjects\IDLua\src\run\NginxProcessHandler.java LuaProcessHandler.java
ren D:\IdeaProjects\IDLua\src\run\NginxReloadAction.java LuaReloadAction.java
ren D:\IdeaProjects\IDLua\src\run\NginxRunConfiguration.java LuaRunConfiguration.java
ren D:\IdeaProjects\IDLua\src\run\NginxRunProfileState.java LuaRunProfileState.java
ren D:\IdeaProjects\IDLua\src\run\NginxRunSettingsEditor.java LuaRunSettingsEditor.java
ren D:\IdeaProjects\IDLua\src\run\NginxRunSettingsForm.form LuaRunSettingsForm.form
ren D:\IdeaProjects\IDLua\src\run\NginxRunSettingsForm.java LuaRunSettingsForm.java
